@FitnessTracker.Api_HostAddress = http://localhost:5179

GET {{FitnessTracker.Api_HostAddress}}/api/workouts
Accept: application/json

###

POST {{FitnessTracker.Api_HostAddress}}/api/workouts
Content-Type: application/json

{
	"name": "Morning Run",
	"durationMinutes": 35,
	"date": "2026-04-01T06:30:00Z",
	"notes": "Easy pace"
}

###
