// <auto-generated />
using System;
using FitnessTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401091018_AddExerciseLogs")]
    partial class AddExerciseLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.ExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseLogs");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.ExerciseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            MuscleGroup = 0,
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            MuscleGroup = 0,
                            Name = "Flat Bench Press"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            MuscleGroup = 0,
                            Name = "Seated Butterfly"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            MuscleGroup = 0,
                            Name = "Push-ups"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            MuscleGroup = 1,
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 2,
                            MuscleGroup = 1,
                            Name = "Overhead Dumbbell Extension"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 3,
                            MuscleGroup = 1,
                            Name = "Single Arm Cable Pushdown"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 4,
                            MuscleGroup = 1,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 1,
                            MuscleGroup = 2,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 2,
                            MuscleGroup = 2,
                            Name = "Seated Row"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 3,
                            MuscleGroup = 2,
                            Name = "One Arm Dumbbell Row"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 4,
                            MuscleGroup = 2,
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 1,
                            MuscleGroup = 3,
                            Name = "Rear Delt Fly"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 2,
                            MuscleGroup = 3,
                            Name = "Lateral Raises"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 3,
                            MuscleGroup = 3,
                            Name = "Seated Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 4,
                            MuscleGroup = 3,
                            Name = "Shrugs"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 1,
                            MuscleGroup = 4,
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 2,
                            MuscleGroup = 4,
                            Name = "Preacher Curl"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 3,
                            MuscleGroup = 4,
                            Name = "Cable Curl"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 4,
                            MuscleGroup = 4,
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 1,
                            MuscleGroup = 5,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 2,
                            MuscleGroup = 5,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 3,
                            MuscleGroup = 5,
                            Name = "Hamstring Curl"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 4,
                            MuscleGroup = 5,
                            Name = "Calf Raises"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedMuscleGroups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
