// <auto-generated />
using System;
using FitnessTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422093228_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.ExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("ExerciseTemplateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("bit");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTemplateId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExerciseLogs");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.ExerciseObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExerciseObjectTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "dumbel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "bar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "machine"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.ExerciseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseObjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseObjectTypeId");

                    b.ToTable("ExerciseTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            ExerciseObjectTypeId = 1,
                            MuscleGroup = 0,
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            ExerciseObjectTypeId = 2,
                            MuscleGroup = 0,
                            Name = "Flat Bench Press"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 0,
                            Name = "Seated Butterfly"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            ExerciseObjectTypeId = 1,
                            MuscleGroup = 0,
                            Name = "Push-ups"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 1,
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 2,
                            ExerciseObjectTypeId = 1,
                            MuscleGroup = 1,
                            Name = "Overhead Dumbbell Extension"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 3,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 1,
                            Name = "Single Arm Cable Pushdown"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 4,
                            ExerciseObjectTypeId = 2,
                            MuscleGroup = 1,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 1,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 2,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 2,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 2,
                            Name = "Seated Row"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 3,
                            ExerciseObjectTypeId = 1,
                            MuscleGroup = 2,
                            Name = "One Arm Dumbbell Row"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 4,
                            ExerciseObjectTypeId = 2,
                            MuscleGroup = 2,
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 1,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 3,
                            Name = "Rear Delt Fly"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 2,
                            ExerciseObjectTypeId = 1,
                            MuscleGroup = 3,
                            Name = "Lateral Raises"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 3,
                            ExerciseObjectTypeId = 1,
                            MuscleGroup = 3,
                            Name = "Seated Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 4,
                            ExerciseObjectTypeId = 2,
                            MuscleGroup = 3,
                            Name = "Shrugs"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 1,
                            ExerciseObjectTypeId = 2,
                            MuscleGroup = 4,
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 2,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 4,
                            Name = "Preacher Curl"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 3,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 4,
                            Name = "Cable Curl"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 4,
                            ExerciseObjectTypeId = 1,
                            MuscleGroup = 4,
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 1,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 5,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 2,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 5,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 3,
                            ExerciseObjectTypeId = 3,
                            MuscleGroup = 5,
                            Name = "Hamstring Curl"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 4,
                            ExerciseObjectTypeId = 2,
                            MuscleGroup = 5,
                            Name = "Calf Raises"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WeightBar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("weight_bar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = 5m
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = 7.5m
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = 10m
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Value = 12.5m
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Value = 15m
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Value = 17.5m
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Value = 20m
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Value = 22.5m
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Value = 25m
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Value = 27.5m
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Value = 30m
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Value = 32.5m
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Value = 35m
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WeightDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("weight_db", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = 2.5m
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = 5m
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = 7.5m
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Value = 10m
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Value = 12m
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Value = 12.5m
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Value = 14m
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Value = 15m
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Value = 16m
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Value = 17.5m
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Value = 20m
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Value = 24m
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WeightMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("weight_machine", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = 5m
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = 10m
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = 15m
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Value = 20m
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Value = 25m
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Value = 30m
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Value = 35m
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Value = 40m
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Value = 45m
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Value = 50m
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Value = 55m
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Value = 60m
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Value = 65m
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Value = 70m
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Value = 75m
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Value = 80m
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Value = 85m
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Value = 90m
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            Value = 95m
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            Value = 100m
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedMuscleGroups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkoutTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTypeId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkoutTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "push",
                            Name = "Push"
                        },
                        new
                        {
                            Id = 2,
                            Code = "pull",
                            Name = "Pull"
                        },
                        new
                        {
                            Id = 3,
                            Code = "leg-shoulder",
                            Name = "Leg + Shoulder"
                        },
                        new
                        {
                            Id = 4,
                            Code = "upper",
                            Name = "Upper"
                        },
                        new
                        {
                            Id = 5,
                            Code = "lower",
                            Name = "Lower"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.ExerciseLog", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.ExerciseTemplate", "ExerciseTemplate")
                        .WithMany()
                        .HasForeignKey("ExerciseTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitnessTracker.Api.Models.WorkoutSession", "WorkoutSession")
                        .WithMany()
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ExerciseTemplate");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.ExerciseTemplate", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.ExerciseObjectType", "ExerciseObjectType")
                        .WithMany()
                        .HasForeignKey("ExerciseObjectTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExerciseObjectType");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSession", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.WorkoutType", "WorkoutType")
                        .WithMany()
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkoutType");
                });
#pragma warning restore 612, 618
        }
    }
}
